baseURL = "https://emsenn.net/makhasa-nursery"
languageCode = "en-us"
enableEmoji = true
title = "makhasa nursery & workshop"

theme = ["nursery-website-theme"]
[taxonomies]
  plant = "plants"
  location = "locations"
[markup.goldmark.renderer]
  unsafe= true
[params]
  author = "emsenn"
  email = "emsenn@emsenn.net"
